name = "CommutativeRings"
uuid = "a6d4fa9c-9e0b-4795-89f3-f481b7b5e384"
license = "MIT"
authors = ["Klaus Crusius <KlausC@users.noreply.github.com>"]
repo = "https://github.com/KlausC/CommutativeRings.jl"
version = "0.6.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Aqua = "0.8"
Polynomials = "1,2,3,4"
Primes = "0.5"
julia = "1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,1.10,1.11"
LinearAlgebra = "1"
Random = "1"
Test = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Primes", "Random", "Polynomials", "LinearAlgebra"]
