name = "CommutativeRings"
uuid = "a6d4fa9c-9e0b-4795-89f3-f481b7b5e384"
license = "MIT"
authors = ["Klaus Crusius <klaus.crusius@web.de>"]
repo = "https://github.com/KlausC/CommutativeRings.jl"
version = "0.3.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"
Primes = "0.5"
